- title: "AI×心理学 LP最適化"
  subtitle: "科学的根拠に基づく高速PDCA"
  icon: "🧠"
  url: "/services/lp-optimization/"
  story: "CVR0.8%で悩んでいたECサイト経営者"
  detail: "3週間でCVR2.1%に改善、売上278%向上を実現"
  features:
    - title: "A/Bテスト自動化"
      metric: "+267% CVR"
    - title: "心理トリガー分析"
      metric: "42% 離脱減"
    - title: "リアルタイム最適化"
      metric: "3週間で完了"

- title: "顧客心理データ分析"
  subtitle: "行動予測AIで売上を科学する"
  icon: "📊"
  url: "/services/customer-analysis/"
  story: "「なぜ売れないのか分からない」美容室オーナー"
  detail: "データ分析で客単価38%向上、リピート率67%改善"
  features:
    - title: "購買行動予測"
      metric: "+187% 精度"
    - title: "顧客セグメント分析"
      metric: "8つのタイプ識別"
    - title: "LTV最大化戦略"
      metric: "+45% LTV向上"

- title: "AI自動化マーケティング"
  subtitle: "24/7稼働するAI営業マン"
  icon: "🤖"
  url: "/services/ai-automation/"
  story: "深夜2時でも問い合わせが来るように"
  detail: "自動化により営業効率400%向上、人件費50%削減"
  features:
    - title: "チャットボット構築"
      metric: "24/7 対応"
    - title: "メール自動配信"
      metric: "+156% 開封率"
    - title: "SNS自動投稿"
      metric: "週40時間削減"

- title: "統合マーケティング戦略"
  subtitle: "オンライン・オフライン完全連携"
  icon: "🎯"
  url: "/services/integrated-marketing/"
  story: "バラバラだった施策を統合したい経営者"
  detail: "全チャネル連携でROAS320%向上を達成"
  features:
    - title: "全チャネル分析"
      metric: "15媒体統合"
    - title: "顧客行動追跡"
      metric: "100% 可視化"
    - title: "ROI最適化"
      metric: "+320% ROAS"