# Site settings
title: "AI×心理学で売上を科学する | Leadfive"
email: leadfive.138@gmail.com
description: >-
  人間の8つの本能を理解し、AIで最適化。予測可能な成長をあなたのビジネスに。
baseurl: ""
url: "https://leadfive-jekyll.netlify.app"
lang: ja

# Company information
company:
  name: "合同会社Leadfive"
  address: "大阪府大阪市北区梅田１−１３−１大阪梅田ツインタワーズ・サウス１５階"
  phone: "06-7713-6747"
  email: "leadfive.138@gmail.com"
  representative: "山下　公一"
  established: "2024年4月8日"

# フォーム設定
forms:
  contact_email: "leadfive.138@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  services:
    output: true
    permalink: /services/:path/
  case_studies:
    output: true
    permalink: /case-studies/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# SEO
twitter:
  username: leadfive
  card: summary_large_image

social:
  name: LeadFive
  links:
    - https://twitter.com/leadfive
    - https://www.facebook.com/leadfive
    - https://www.linkedin.com/company/leadfive

# Analytics
google_analytics: UA-XXXXXXXXX-X